spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/home_services
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: validate

  flyway:
    enabled: true

management:
  endpoints:
    web:
      exposure:
        include: health,info
